version: "2"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    environment:
      - "INFLUXDB_DB=temperatures"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=admin"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./influx_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel"
    ports:
      - "3000:3000"
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./grafana_data:/var/lib/grafana

  mi_reader:
    image: akosfonod/xiaomi-mija-reader:amd64
    container_name: midevenv
    hostname: mija_reader
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./config:/xiaomi/config

volumes: 
  influx_data:
  grafana_data:
  config: